### ISSUE TITLE
Manticore and Etheno not working

### ISSUE THREAD

**Issue by Deivitto** [Deivitto/auditor-docker#24]
## To do: 
Check if using venv can make it work 

## Example: 
$ manticore
Traceback (most recent call last):
  File "/home/whitehat/.manticore_env/bin/manticore", line 5, in <module>
    from manticore.__main__ import main
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/__init__.py", line 10, in <module>
    from .ethereum.manticore import ManticoreEVM
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/ethereum/__init__.py", line 3, in <module>
    from .manticore import ManticoreEVM, config
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/ethereum/manticore.py", line 15, in <module>
    from ..core.manticore import ManticoreBase, ManticoreError
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/core/manticore.py", line 29, in <module>
    from .worker import (
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/core/worker.py", line 4, in <module>
    from .state_pb2 import StateList, MessageList, State, LogMessage
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/manticore/core/state_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/whitehat/.manticore_env/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-update

**Comment by Deivitto** [comment]
Solved:
https://github.com/Deivitto/auditor-docker/commit/c583f239417fbdd0e5e18a2f805b704c2ed933a6
